//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeService
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string empID { get; set; }
        public string empName { get; set; }
        public string empPhNo { get; set; }
        public string empEmail { get; set; }
        public string empAdd { get; set; }
    }
}
